User can view List of Products for ProductType Details
the-devastating-chickens/BangazonSite pull request #32
Opened 2019-07-17 20:25 UTC by bluemorgan23

User can view List of Products for ProductType Details

# Description

Created a view model for the product type details view. This view model has two properties: the ProductType and the List<Product> which represents products of that type.

Fixes Issue # [3](https://github.com/the-devastating-chickens/BangazonSite/issues/3)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

- [ ] This change requires a documentation update

# Testing Instructions

1. `git fetch --all`
1. `git checkout cm-wednesday`
1. Review the code within the ProductTypesController and make sure the comments are well written.
1. Review the code within the ProductTypeDetailsViewModel and make sure the comments are well written.
1. Run the application
1. Navigate to product types and select details of a few of the product types. (Tools should have a few listed below)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added test instructions that prove my fix is effective or that my feature works

2019-07-17 20:34 UTC, rosewisotzky approved these changes
GREAT JOB! THIS PR CURED MY SEASONAL ALLERGIES!

2019-07-17 20:57 UTC, rosewisotzky approved these changes

2019-07-18 01:25 UTC, wlmathison requested changes
Looking good. Only suggestion I have is that if I type a number into the address bar after details that does not exist or type in something that is not a number I get a 500 error. Can we address this so Andy can't break it and then we win.

2019-07-18 14:03 UTC, wlmathison approved these changes
So I was totally looking at it wrong. Everything looks good. Nice job Chris.

2019-07-18 14:05 UTC, merged